services:
  dashboard:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      # You can put it directly or in a .env
      # Example: Basic QWRtaW46QWRtaW4=
      - PALWORLD_BASIC_AUTH=${PALWORLD_BASIC_AUTH}
    volumes:
      - ./config:/config
      - ./data:/data
      # dev-only mount (safe even in prod, but optional)
      - ./:/app
      - /app/node_modules
